POST http://localhost:3000/api/product HTTP/1.1
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJieWlubGlubUBnbWFpbC5jb20iLCJuYW1lIjoiQnJheWFuIFlpbiBMaW4iLCJpYXQiOjE3MjQwOTk2OTksImV4cCI6MTcyNDEyODQ5OX0.FkPCaXihzDu60qe9zmSjYiCSrhJ_URJ6YPwGT92TVvc
Content-Type: application/json

{
  "name": "Jamon",
  "stock": 100,
  "volume": "Unidades"
}

###